# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_base_version=26.3-rc-1
minecraft_version=26.3-rc-1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=2.5.3
maven_group=me.pigicial
archives_base_name=wikirenderer

# Dependencies
fabric_version=0.160.3+26.3

iris_version=1.11.1+26.2-fabric

# bruh moment id
entity_culling_version=NaRJu6ah

devauth_version=1.2.2

litematica_version=26.2:0.28.3
malilib_version=26.2:0.29.3

# Gifski
gifski_version=1.34.0
gifski_hash=b9b6591aa163123d737353d9c8581efdf3234d28eeaa45329b31da905cd5a996